sudo: required
language: node_js
node_js:
  - "10"

services:
  - docker

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - docker build -t aamirbakhtiar/angular-docker -f Dockefile.dev .

script:
  - docker run aamirbakhtiar/angular-docker npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
