sudo: required
language: node_js
node_js:
  - "10"

services:
  - docker

before_install:
  - docker build -t aamirbakhtiar/angular-docker -f Dockerfile.dev .

script:
  - docker run aamirbakhtiar/angular-docker npm run test-headless
